---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: librespeed
  name: librespeed
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: librespeed
  template:
    metadata:
      labels:
        app.kubernetes.io/name: librespeed
    spec:
      containers:
        - name: librespeed
          image: ghcr.io/librespeed/speedtest@sha256:d251eb8973ffae152714d7d5bd63590df3364edf19dd2b9177d47e8285762a1b
          env:
            - name: MODE
              value: standalone
