apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-default-tls-cert
  namespace: traefik
spec:
  secretName: traefik-default-tls
  dnsNames:
    - "*.lab.paultibbetts.uk"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
