apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data
  namespace: hortusfox
  labels:
    app.kubernetes.io/name: hortusfox
    app.kubernetes.io/component: mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
