komga:
  image:
    repository: docker.io/gotson/komga
    tag: 1.27.0
    pullPolicy: IfNotPresent
  timezone: Europe/London
  service:
    port: 25600
  podSecurityContext:
    supplementalGroups:
      - 3003
  resources:
    requests:
      memory: 512Mi
    limits:
      memory: 1Gi

configPersistence:
  size: 5Gi

mediaPersistence:
  claimName: media-komga
  size: 1Ti
  volumeName: media-komga

ingressRoute:
  host: komga.lab.paultibbetts.uk
  externalDnsTarget: traefik.lab.paultibbetts.uk
