apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: komga-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: komga
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.configPersistence.size }}
