apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mediaPersistence.claimName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: komga
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.mediaPersistence.size }}
  storageClassName: ""
  volumeName: {{ .Values.mediaPersistence.volumeName }}
