cert-manager:
  installCRDs: true
  resources:
    requests:
      memory: 64Mi
  webhook:
    resources:
      requests:
        memory: 64Mi
  cainjector:
    resources:
      requests:
        memory: 64Mi
  startupapicheck:
    resources:
      requests:
        memory: 32Mi
  prometheus:
    enabled: false
    servicemonitor:
      enabled: false
