apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grocy-mealie-sync-data
  namespace: grocy-mealie-sync
  labels:
    app.kubernetes.io/name: grocy-mealie-sync
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
