---
- name: Longhorn
  hosts: longhorn
  gather_facts: true
  become: true
  pre_tasks:
    - name: Update apt cache if required
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
  tasks:
    - name: Longhorn - packages
      block:
        - name: Longhorn - Install required packages
          ansible.builtin.package:
            name:
              - nfs-common
              - open-iscsi

        - name: Longhorn - Enable open-iscsi now and on boot
          ansible.builtin.systemd_service:
            state: started
            enabled: true
            name: open-iscsi

    - name: Longhorn - disk
      block: 
        - name: Longhorn - Partition data disk
          community.general.parted:
            device: /dev/sdb
            number: 1
            state: present

        - name: Longhorn - Enable filesystem on disk
          community.general.filesystem:
            fstype: ext4
            dev: /dev/sdb1

        - name: Longhorn - Mount data disk
          ansible.posix.mount:
            path: /mnt/storage
            src: /dev/sdb1
            fstype: ext4
            state: mounted

    - debug:
        var: groups['longhorn']
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Longhorn - Apply K8s label and annotation
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Node
          metadata:
            name: "{{ item }}"
            labels:
              node.longhorn.io/create-default-disk: config
            annotations:
              node.longhorn.io/default-disks-config: '[ { "name":"longhorn-volume", "path":"/mnt/storage","allowScheduling":true, "storageReserved":0,"tags":[ "nvme" ] } ]'
      loop: "{{ query('inventory_hostnames', 'longhorn') }}"
