traefik:
  deployment:
    dnsConfig:
      nameservers:
        - 10.1.21.2
      searches:
        - lan
    replicas: 3
  ports:
    websecure:
      http3:
        enabled: true
  global:
    checkNewVersion: false
  additionalArguments:
    - "--serversTransport.insecureSkipVerify=true"
    - "--log.level=INFO"
    - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
    - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
    - "--entryPoints.web.http.redirections.entryPoint.permanent=true"
  ingressRoute:
    dashboard:
      enabled: false
  providers:
    kubernetesCRD:
      enabled: true
      allowExternalNameServices: true
    kubernetesIngress:
      enabled: true
      allowExternalNameServices: true
      publishedService:
        enabled: true
  service:
    enabled: true
    type: LoadBalancer
    annotations: {}
    labels: {}
    spec:
      loadBalancerIP: 10.1.21.252 # this should be an IP in the MetalLB range
    loadBalancerSourceRanges: []
    externalIPs: []
