longhorn:
  preUpgradeChecker:
    jobEnabled: false
  longhornManager:
    resources:
      requests:
        memory: 256Mi
  defaultSettings:
    createDefaultDiskLabeledNodes: true
    kubernetesClusterAutoscalerEnabled: true
    defaultDataPath: /var/lib/longhorn
    node-down-pod-deletion-policy: delete-both-statefulset-and-deployment-pod
    storageReservedPercentageForDefaultDisk: 10
  persistence:
    defaultClass: true
    defaultFsType: ext4
    defaultClassReplicaCount: 3
