apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: outline-data
  namespace: outline
  labels:
    app.kubernetes.io/name: outline
    app.kubernetes.io/component: app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
