renovate:
  env:
    LOG_LEVEL: debug
  cronjob:
    schedule: '0 */6 * * *'  # Every 6 hours / 4 times per day
  renovate:
    config: |
      {
        "platform": "gitea",
        "endpoint": "https://gitea.cloud.paultibbetts.uk/api/v1",
        "gitAuthor": "Renovate Bot <bot@renovateapp.com>",
        "autodiscover": true,
        "extends": ["config:recommended", ":dependencyDashboard"],
        "prHourlyLimit": 10,
        "labels": ["dependencies"],
        "packageRules": [
          {
            "matchUpdateTypes": ["patch"],
            "groupName": "patches",
          }
        ]
      }
  existingSecret: renovate-secret
  redis:
    enabled: true
