grafana:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      external-dns.alpha.kubernetes.io/target: "traefik.lab.paultibbetts.uk"
      gethomepage.dev/href: "https://grafana.lab.paultibbetts.uk"
      gethomepage.dev/enabled: "true"
      gethomepage.dev/description: Dashboards
      gethomepage.dev/group: Platform
      gethomepage.dev/icon: grafana.png
      gethomepage.dev/name: Grafana
    hosts:
      - &host grafana.lab.paultibbetts.uk
    tls:
      - secretName: grafana-tls
        hosts:
          - *host
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: monitoring-system
    datasources:
      enabled: true
      searchNamespace: monitoring-system
  grafana.ini:
    server:
      root_url: https://grafana.lab.paultibbetts.uk
  persistence:
    enabled: true
