grafana:
  deploymentStrategy:
    type: Recreate
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      external-dns.alpha.kubernetes.io/target: "traefik.lab.paultibbetts.uk"
      gethomepage.dev/href: "https://grafana.lab.paultibbetts.uk"
      gethomepage.dev/enabled: "true"
      gethomepage.dev/description: Dashboards
      gethomepage.dev/group: Platform
      gethomepage.dev/icon: grafana.png
      gethomepage.dev/name: Grafana
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - &host grafana.lab.paultibbetts.uk
    tls:
      - secretName: grafana-tls
        hosts:
          - *host
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: monitoring-system
    datasources:
      enabled: true
      searchNamespace: monitoring-system
  grafana.ini:
    auth.generic_oauth:
      enabled: true
      name: Kanidm
      client_id: $__file{/etc/secrets/auth_generic_oauth/client_id}
      client_secret: $__file{/etc/secrets/auth_generic_oauth/client_secret}
      scopes: openid,profile,email,groups
      auth_url: https://auth.cloud.paultibbetts.uk/ui/oauth2
      token_url: https://auth.cloud.paultibbetts.uk/oauth2/token
      api_url: https://auth.cloud.paultibbetts.uk/oauth2/openid/grafana/userinfo
      use_pkce: true
      use_refresh_token: true
      allow_sign_up: true
      login_attribute_path: preferred_username
      groups_attribute_path: groups
      role_attribute_path: contains(grafana_role[*], 'GrafanaAdmin') && 'GrafanaAdmin' || contains(grafana_role[*], 'Admin') && 'Admin' || contains(grafana_role[*], 'Editor') && 'Editor' || 'Viewer'
      allow_assign_grafana_admin: true
    server:
      root_url: https://grafana.lab.paultibbetts.uk
  extraSecretMounts:
    - name: auth-generic-oauth-secret-mount
      secretName: auth-generic-oauth-secret
      defaultMode: 0440
      mountPath: /etc/secrets/auth_generic_oauth
      readOnly: true
  persistence:
    enabled: true
