apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch-data
  namespace: linkwarden
  labels:
    app.kubernetes.io/name: linkwarden
    app.kubernetes.io/component: meilisearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
