apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: searxng
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: searxng
  annotations:
    external-dns.alpha.kubernetes.io/target: "traefik.lab.paultibbetts.uk"
    gethomepage.dev/href: "https://searxng.lab.paultibbetts.uk"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Privacy-respecting metasearch
    gethomepage.dev/group: Apps
    gethomepage.dev/icon: searxng.png
    gethomepage.dev/name: SearXNG
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`searxng.lab.paultibbetts.uk`)
      kind: Rule
      services:
        - name: searxng
          port: http
  tls: {}
