apiVersion: v1
kind: ConfigMap
metadata:
  name: matrix-config
  labels:
    app.kubernetes.io/name: matrix
data:
  tuwunel.toml: |
    [global]
    server_name = "matrix.lab.paultibbetts.uk"
    database_path = "/data"
    address = ["0.0.0.0"]
    port = 6167
    allow_registration = true
    allow_federation = false
