apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix-data
  labels:
    app.kubernetes.io/name: matrix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
