apiVersion: v1
kind: Service
metadata:
  name: matrix
  labels:
    app.kubernetes.io/name: matrix
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: matrix
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
