---
- name: install ansible support packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ ansible_support_packages }}"

- name: create gitea group
  ansible.builtin.group:
    name: "{{ gitea_group }}"
    state: present

- name: create gitea user
  ansible.builtin.user:
    name: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    home: "{{ gitea_working_directory }}"
    comment: Gitea

- name: ensure directory exists
  ansible.builtin.file:
    path: "{{ gitea_binary | dirname }}"
    state: directory
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: 0755
    recurse: true

- name: download gitea binary
  ansible.builtin.get_url:
    url: "{{ gitea_download_url }}"
    dest: "{{ gitea_binary }}"
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: 0755

- name: generate gitea envfile
  ansible.builtin.template:
    src: gitea.env.j2
    dest: "{{ gitea_envfile }}"
  notify: restart gitea

- name: create the gitea systemd unit file
  ansible.builtin.template:
    src: gitea.unit.j2
    dest: "{{ systemd_units_dir }}/gitea.service"
  when: ansible_service_mgr == "systemd"
  notify: restart gitea

- name: create the gitea init.d start-up script
  ansible.builtin.template:
    src: gitea.init.j2
    dest: "{{ initd_conf_dir }}/gitea"
    mode: 0755
  when: ansible_service_mgr != "systemd"
  notify: restart gitea

- name: enable and start the gitea web service
  ansible.builtin.service:
    name: gitea
    state: started
    enabled: yes
