apiVersion: v1
kind: ConfigMap
metadata:
  name: gancio-env
  namespace: gancio
  labels:
    app.kubernetes.io/name: gancio
data:
  .env: |
    BASEURL=https://gancio.lab.paultibbetts.uk
    HOST=0.0.0.0
    PORT=13120
    LOG_LEVEL=info
    LOG_PATH=./logs
    DB_DIALECT=sqlite
    DB_STORAGE=./gancio.sqlite
    DB_LOGGING=false
    USER_LOCALE=./user_locale
    UPLOAD_PATH=./uploads
    ALLOW_ACCESS_TO_HIDDEN_SERVICE=false
