apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gancio-data
  namespace: gancio
  labels:
    app.kubernetes.io/name: gancio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
