apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    traefik: true
  settings.yaml: |
    bookmarksStyle: icons
    layout:
      Apps:
        icon: si-appstore
      Platform:
        icon: mdi-layers
      System:
        icon: mdi-chip
    providers:
      longhorn:
        url: https://longhorn.lab.paultibbetts.uk
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Cloud:
        - Homepage:
            - abbr: Home
              icon: homepage
              href: https://homepage.cloud.paultibbetts.uk
        - Gitea:
            - abbr: Git
              icon: gitea
              href: https://gitea.cloud.paultibbetts.uk
  proxmox.yaml: ""
  services.yaml: |
    - MonPi:
        - Uptime Kuma:
            href: https://uptime.cloud.paultibbetts.uk/status/lab
            description: Uptime
            icon: uptime-kuma
            widget:
              type: uptimekuma
              url: https://uptime.cloud.paultibbetts.uk
              slug: lab
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: false
          memory: false
          showLabel: true
          label: "TuringPi"
        nodes:
          show: false
          cpu: false
          memory: false
          showLabel: true
    - resources:
        expanded: false
        cpu: false
        memory: false
        network: false
    - longhorn:
        expanded: true
        total: true
        labels: true
        nodes: false
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
