apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    traefik: true
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Cloud:
        - Homepage:
            - abbr: Hom
              href: https://homepage.cloud.paultibbetts.uk
        - Gitea:
            - abbr: Git
              href: https://gitea.cloud.paultibbetts.uk
  services.yaml: |
  #  - My First Group:
  #      - My First Service:
  #          href: http://localhost/
  #          description: Homepage is awesome
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: false
          label: "cluster"
        nodes:
          show: false
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: false
        cpu: false
        memory: false
        network: false
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
