apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    traefik: true
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Cloud:
        - Homepage:
            - abbr: Hom
              href: https://homepage.cloud.paultibbetts.uk
        - Gitea:
            - abbr: Git
              href: https://gitea.cloud.paultibbetts.uk
  services.yaml: |
    - Cloud:
        - Uptime:
            href: https://uptime.cloud.paultibbetts.uk
            description: Uptime Kuma
            widget:
              type: uptimekuma
              url: https://uptime.cloud.paultibbetts.uk
              slug: cloud
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: false
          memory: false
          showLabel: true
          label: "TuringPi"
        nodes:
          show: true
          cpu: false
          memory: false
          showLabel: true
    - resources:
        expanded: false
        cpu: false
        memory: false
        network: false
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
