apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opengist-tls-cert
  namespace: opengist
spec:
  secretName: opengist-tls
  dnsNames:
    - opengist.lab.paultibbetts.uk
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production

