apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: penpot-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: penpot
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
