apiVersion: v1
kind: Service
metadata:
  name: penpot-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: penpot
    app.kubernetes.io/component: postgres
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  selector:
    app.kubernetes.io/name: penpot
    app.kubernetes.io/component: postgres
