apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: yamtrack-api
  namespace: yamtrack-api
  labels:
    app.kubernetes.io/name: yamtrack-api
  annotations:
    external-dns.alpha.kubernetes.io/target: "traefik.lab.paultibbetts.uk"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`yamtrack-api.lab.paultibbetts.uk`)
      kind: Rule
      services:
        - name: yamtrack-api
          port: http
  tls: {}
