apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yamtrack-api-data
  namespace: yamtrack-api
  labels:
    app.kubernetes.io/name: yamtrack-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
