apiVersion: v1
kind: Service
metadata:
  name: yamtrack-api-redis
  namespace: yamtrack-api
  labels:
    app.kubernetes.io/name: yamtrack-api
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: yamtrack-api
    app.kubernetes.io/component: redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: redis
