newt:
  global:
    deploymentAnnotations:
      configmap.reloader.stakater.com/reload: newt-newt-homelab-blueprint
      reloader.stakater.com/rollout-strategy: restart
    notes:
      defaultTraefikTarget: traefik.traefik.svc.cluster.local:443
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
        ephemeral-storage: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
        ephemeral-storage: 256Mi

  newtInstances:
    - name: homelab
      enabled: true
      auth:
        existingSecretName: newt-main-tunnel-auth
      configPersistence:
        enabled: true
        type: emptyDir
        mountPath: /var/lib/newt
        fileName: config.json
      blueprintFile: /etc/newt/blueprints/homelab.yaml
      blueprintData: |
        public-resources:
          dev-wildcard:
            name: Dev Wildcard
            mode: http
            full-domain: "*.dev.lab.paultibbetts.uk"
            tls-server-name: pangolin-dev.dev.lab.paultibbetts.uk
            enabled: true
            targets:
              - hostname: traefik.traefik.svc.cluster.local
                port: 443
                method: https
          preview-wildcard:
            name: Preview Wildcard
            mode: http
            full-domain: "*.preview.lab.paultibbetts.uk"
            tls-server-name: pangolin-preview.preview.lab.paultibbetts.uk
            enabled: true
            targets:
              - hostname: traefik.traefik.svc.cluster.local
                port: 443
                method: https
          kavita:
            name: Kavita
            protocol: http
            full-domain: "kavita.lab.paultibbetts.uk"
            tls-server-name: "kavita.lab.paultibbetts.uk"
            enabled: true
            targets:
              - hostname: traefik.traefik.svc.cluster.local
                port: 443
                method: https
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
          ephemeral-storage: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
          ephemeral-storage: 256Mi
