#!/usr/bin/env bash
# https://docs.siderolabs.com/talos/v1.12/getting-started/prodnotes#step-12-manage-your-talos-configuration-file

source "$(dirname "$0")/lib/env"

mkdir -p ~/.talos
cp ./talosconfig ~/.talos/config
export TALOSCONFIG=~/.talos/config

# https://docs.siderolabs.com/talos/v1.12/getting-started/prodnotes#step-13-set-endpoints-of-your-control-plane-nodes

talosctl config endpoint "${CONTROL_PLANE_IP[@]}"
