#!/usr/bin/env bash
# https://docs.siderolabs.com/talos/v1.12/getting-started/prodnotes#step-15-get-kubernetes-access

source "$(dirname "$0")/lib/env"

: "${CONTROL_PLANE_IP:?CONTROL_PLANE_IP is required}"

talosctl kubeconfig --nodes "${CONTROL_PLANE_IP[0]}"
