---
postgresql_databases:
  - name: mealie

postgresql_users:
  - name: mealie
    password: mealie
    db: mealie
    priv: ALL

postgresql_hba_entries:
  - { type: local, database: all, user: postgres, auth_method: peer }
  - { type: local, database: all, user: all, auth_method: peer }
  - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5 }
  - { type: host, database: all, user: all, address: '::1/128', auth_method: md5 }
  - { type: host, database: mealie, user: mealie, address: '192.168.1.0/24', auth_method: md5 }

postgres_users_no_log: false

