web-app:
  replicaCount: 1
  image:
    value: gitea.cloud.paultibbetts.uk/paul/indiewebify-me:slim-migration-9d4fda1c0538
    pullPolicy: IfNotPresent
  containerPort: 80
  env:
    - name: APP_ENV
      value: production
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  ingress:
    enabled: true
    className: traefik
    annotations:
      external-dns.alpha.kubernetes.io/target: traefik.lab.paultibbetts.uk
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
      - host: indiewebify-me-slim-migration.preview.lab.paultibbetts.uk
        paths:
          - path: /
            pathType: Prefix
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi
