homebox:
  env:
    TZ: Europe/London
    HBOX_DATABASE_DRIVER: postgres

  # For more information checkout: https://artifacthub.io/packages/helm/bitnami/postgresql
  postgresql:
    enabled: true
    auth:
      username: homebox-user
      password: homebox-password
      database: homebox-db

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      external-dns.alpha.kubernetes.io/target: "traefik.lab.paultibbetts.uk"
      gethomepage.dev/href: "https://homebox.lab.paultibbetts.uk"
      gethomepage.dev/enabled: "true"
      gethomepage.dev/description: Inventory management
      gethomepage.dev/group: Apps
      gethomepage.dev/icon: homebox.png
      gethomepage.dev/name: Homebox
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: &host homebox.lab.paultibbetts.uk
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: homebox-tls
        hosts:
          - *host

  persistence:
    storageClass: longhorn
