apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: books-kavita
  namespace: kavita
  labels:
    app: kavita
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: ""
  volumeName: books-kavita
