apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-config
  namespace: kavita
  labels:
    app: kavita
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
