plane-ce:
  planeVersion: v1.2.1

  ingress:
    enabled: false
    appHost: plane.lab.paultibbetts.uk
    ingressClass: traefik

  external_secrets:
    rabbitmq_existingSecret: plane-rabbitmq
    pgdb_existingSecret: plane-pgdb
    doc_store_existingSecret: plane-docstore
    app_env_existingSecret: plane-app-env
    live_env_existingSecret: plane-live-env

  redis:
    local_setup: true
    storageClass: longhorn
    volumeSize: 1Gi

  postgres:
    local_setup: true
    storageClass: longhorn
    volumeSize: 10Gi

  rabbitmq:
    local_setup: true
    storageClass: longhorn
    volumeSize: 1Gi

  minio:
    local_setup: true
    storageClass: longhorn
    volumeSize: 20Gi

  web:
    pullPolicy: IfNotPresent
    memoryRequest: 128Mi
    memoryLimit: 256Mi

  space:
    pullPolicy: IfNotPresent
    memoryRequest: 128Mi
    memoryLimit: 256Mi

  admin:
    pullPolicy: IfNotPresent
    memoryRequest: 128Mi
    memoryLimit: 256Mi

  live:
    pullPolicy: IfNotPresent
    memoryRequest: 128Mi
    memoryLimit: 256Mi

  api:
    pullPolicy: IfNotPresent
    memoryRequest: 512Mi
    memoryLimit: 1Gi

  worker:
    pullPolicy: IfNotPresent
    memoryRequest: 512Mi
    memoryLimit: 1Gi

  beatworker:
    pullPolicy: IfNotPresent
    memoryRequest: 512Mi
    memoryLimit: 1Gi

  env:
    minio_endpoint_ssl: false
    cors_allowed_origins: https://plane.lab.paultibbetts.uk
    docstore_bucket: uploads
    doc_upload_size_limit: "5242880"
