woodpecker:
  server:
    env:
      WOODPECKER_GITEA: "true"
      WOODPECKER_GITEA_URL: "https://gitea.cloud.paultibbetts.uk"
      WOODPECKER_HOST: "https://woodpecker.lab.paultibbetts.uk"
    extraSecretNamesForEnvFrom:
      - woodpecker-gitea-oauth
    ingress:
      # -- Enable the ingress for the server component
      enabled: true
      # -- Add annotations to the ingress
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        external-dns.alpha.kubernetes.io/target: "traefik.lab.paultibbetts.uk"
        gethomepage.dev/href: "https://woodpecker.lab.paultibbetts.uk"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: CI
        gethomepage.dev/group: Platform
        gethomepage.dev/icon: woodpecker.png
        gethomepage.dev/name: woodpecker
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      # -- Defines which ingress controller will implement the resource
      ingressClassName: 'traefik'

      hosts:
        - host: &host woodpecker.lab.paultibbetts.uk
          paths:
            - path: /
      tls:
        - secretName: woodpecker-tls
          hosts:
            - *host
