machine:
  install:
    disk: /dev/mmcblk0
  kubelet:
    extraConfig:
      evictionHard:
        memory.available: 512Mi
        nodefs.available: 20Gi
        imagefs.available: 20Gi
  network:
    nameservers:
      - 10.1.21.2
    interfaces:
      - interface: end0
        dhcp: true
        vip:
          ip: 10.1.21.21
  time:
    servers:
      - 0.uk.pool.ntp.org
      - 1.uk.pool.ntp.org
      - 2.uk.pool.ntp.org
      - 3.uk.pool.ntp.org
cluster:
  allowSchedulingOnControlPlanes: true
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: disk.transport == 'nvme' && !system_disk
