penpot:
  fullnameOverride: penpot

  config:
    publicUri: https://penpot.lab.paultibbetts.uk
    flags: enable-registration enable-login-with-password disable-email-verification
    existingSecret: penpot-secrets
    secretKeys:
      apiSecretKey: api-secret-key
    telemetryEnabled: false
    postgresql:
      host: penpot-postgres
      username: penpot
      database: penpot
      existingSecret: penpot-secrets
      secretKeys:
        passwordKey: password
    redis:
      host: penpot-valkey
  backend:
    resources:
      requests:
        memory: 512Mi
  frontend:
    resources:
      requests:
        memory: 128Mi
  exporter:
    resources:
      requests:
        memory: 128Mi
  mcp:
    resources:
      requests:
        memory: 128Mi

  persistence:
    assets:
      enabled: true
      size: 20Gi
      accessModes:
        - ReadWriteMany

  ingress:
    enabled: false
