apiVersion: apps/v1
kind: Deployment
metadata:
  name: yamtrack
  labels:
    app.kubernetes.io/name: yamtrack
    app.kubernetes.io/component: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: yamtrack
  template:
    metadata:
      labels:
        app.kubernetes.io/name: yamtrack
        app.kubernetes.io/component: app
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: yamtrack
          image: ghcr.io/fuzzygrim/yamtrack:0.25.3
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Europe/London
            - name: REDIS_URL
              value: redis://redis:6379
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: yamtrack-env
                  key: SECRET
            - name: URLS
              valueFrom:
                secretKeyRef:
                  name: yamtrack-env
                  key: URLS
            - name: STEAM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: yamtrack-env
                  key: STEAM_API_KEY
          ports:
            - containerPort: 8000
              name: http
          resources:
            requests:
              memory: 256Mi
          volumeMounts:
            - name: data
              mountPath: /yamtrack/db
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: yamtrack-data
