apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yamtrack-data
  namespace: yamtrack
  labels:
    app.kubernetes.io/name: yamtrack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
