apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: semaphore-data
  namespace: semaphore
  labels:
    app.kubernetes.io/name: semaphore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
